### ISSUE TITLE
Doesn't post to slack

### ISSUE THREAD

**Issue by alekseevpg** [Tapadoo/TCSlackNotifierPlugin#14]
All configurations seems ok. 
I see all the config in TC, but still no messages for slack.

TeamCity Professional 8.1.4 (build 30168)

And I can't see Slack Notification Settings in My Tools & Settings 

![screenshot 2014-10-15 12 34 44](https://cloud.githubusercontent.com/assets/2044497/4642537/3e5fe920-5446-11e4-9c73-e4df150f4602.png)

Any thoughts? :)

**Comment by Sangdol** [comment]
In my case, it doesn't post and Slack Notifier is not shown on the integrations list. I uploaded `TCSlackNotifierPlugin-master.zip` file and added config in the `.BuildServer/config/main-config.xml` file. What could be the problem?
