### ISSUE TITLE
how to disable notification per project level?

### ISSUE THREAD

**Issue by dianasp** [Tapadoo/TCSlackNotifierPlugin#18]
this is a question on how to disable notification per project level. since some test project in teamcity doesn't need to send out build message.
 
So, should I add below code in plugin-settings.xml, and set enable="false"?
![image](https://cloud.githubusercontent.com/assets/13155340/8751866/019e7df6-2c7e-11e5-80c6-07ad19693d54.png)

**Comment by jasonconnery** [comment]
Yup, that'll disable it per project.
