### ISSUE TITLE
Feature request: global way to map git users to slack users

### ISSUE THREAD

**Issue by hammett** [Tapadoo/TCSlackNotifierPlugin#19]
Maybe I failed to find it, but sometimes the usernames wont match, and if I could provide that mapping.. that'd be great. 

![image](https://cloud.githubusercontent.com/assets/139550/9369055/422a497a-469d-11e5-9aff-756cc98db5bc.png)

**Comment by jasonconnery** [comment]
Names show up if teamcity detects its own users. If teamcity username vcs settings map to git names, they will show up, otherwise it's a teamcity configuration issue.
