### ISSUE TITLE
Branch based configurations should show branch in Slack messages

### ISSUE THREAD

**Issue by bytenik** [Tapadoo/TCSlackNotifierPlugin#6]
For example, I get messages such as:

`Project 'FunnelFire :: Feature Branches' build started.`

This configuration could be one of any number of different branches. It should perhaps say:

`Project 'FunnelFire :: Feature Branches (feature/new-cool-thing)' build started.`

**Comment by neouser99** [comment]
+1

I'm not all to familiar with the stuff for TeamCity (or Java). Would be happy to submit a pull request, but I need a little bit of direction. Best I could find is this?

https://github.com/jonnyzzz/TeamCity.GitHub/blob/5c2868bdcf8e42fb348d175efb1ea586f6383575/server/src/jetbrains/teamcilty/github/ChangeStatusListener.java#L94
